# CodeRabbit configuration file
# See https://docs.coderabbit.ai/guides/configure-coderabbit

reviews:
  # Enable auto-reviews for all branches (not just default branch)
  auto_review:
    enabled: true
    # Review all pull requests, regardless of target branch
    base_branches:
      - ".*"

  # Exclude documentation files from review
  path_filters:
    - "!docs/**"
    - "!**/*.md"

  # Review profile: assertive (more feedback) or chill (less feedback)
  profile: assertive

  # Post review status as a check
  review_status: true
